# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-04 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=25)),
                ('file', models.FileField(upload_to=b'')),
            ],
        ),
    ]
