"""
django-storages settings
"""
from .ENV import ENV_VAR

AWS_ACCESS_KEY_ID = ENV_VAR('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = ENV_VAR('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = ENV_VAR('AWS_STORAGE_BUCKET_NAME')
AWS_DEFAULT_ACL = None
AWS_S3_REGION_NAME = 'us-east-1'
